apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-static-data-pvc
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-path  # optional; could omit if it's default
