apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-data
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
