apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: traefik
          volumeMounts:
            - name: acme
              mountPath: /data
      volumes:
        - name: acme
          hostPath:
            path: /data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik
data:
  traefik.yml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    certificatesResolvers:
      le:
        acme:
          email: admin@somehostname.local
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
