apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: nodeport
  create_postgres_container: true
  postgres_storage_class: ""
  postgres_volume_capacity: 40Gi
  extra_volumes:
    postgres-data:
      persistentVolumeClaim:
        claimName: awx-pvc
  extra_volume_mounts:
    postgres-data:
      mountPath: /var/lib/pgsql/data
      subPath: userdata
