apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: nodeport
  create_postgres_container: true
  postgres_storage_class: local-path  # ← set explicitly!
  postgres_volume_capacity: 8Gi
  postgres_data_volume_init: true
