apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: ClusterIP
  ingress_type: none
  hostname: awx.somehostname.local
  replicas: 1
  postgres_storage_class: local-path
  postgres_resource_requirements: {}

  extraVolumeMounts:
    - name: awx-data
      mountPath: /var/lib/awx

  extraVolumes:
    - name: awx-data
      persistentVolumeClaim:
        claimName: awx-data
