apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-pv
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/awx"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-pvc
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
