apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/4FunAndTesting/awx-instance.git
    path: awx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
