apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ansible/awx-operator.git
    targetRevision: devel  # stable releases are under tags (e.g., 2.14.0)
    path: deploy/helm
    helm:
      releaseName: awx-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
