apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 35.2.0
    helm:
      releaseName: traefik
      values: |
        ports:
          web:
            port: 80
            expose:
              default: true
            exposedPort: 80
            protocol: TCP
          websecure:
            port: 443
            expose:
              default: true
            exposedPort: 443
            protocol: TCP

        ingressRoute:
          dashboard:
            enabled: true

        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true

        additionalArguments:
          - "--certificatesresolvers.le.acme.email=admin@somehostname.local"
          - "--certificatesresolvers.le.acme.storage=/data/acme.json"
          - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
          - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
          - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

        persistence:
          enabled: true
          storageClass: local-path
          accessMode: ReadWriteOnce
          size: 1Gi
          path: /data
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
