apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 35.2.0
    helm:
      releaseName: traefik
      values: |
        ports:
          web:
            port: 80
            expose:
              default: true
            exposedPort: 80
            protocol: TCP
          websecure:
            port: 443
            expose:
              default: true
            exposedPort: 443
            protocol: TCP
          dashboard:
            port: 9000
            expose:
              default: true
            exposedPort: 9000
            protocol: TCP

        service:
          dashboard:
            enabled: true
            type: NodePort
            ports:
              - port: 9000
                targetPort: 9000
                nodePort: 30900
                protocol: TCP

        ingressRoute:
          dashboard:
            enabled: true

        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true

        additionalArguments:
          - "--certificatesresolvers.le.acme.email=admin@somehostname.local"
          - "--certificatesresolvers.le.acme.storage=/data/acme.json"
          - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"

        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 1Gi
          path: /data
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
